todotest/Models/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace todotest.Models
{
    public class Todo
    {
        public int TodoId { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Completed { get; set; }
        [Required]
        public string Description { get; set; }
        public bool Done { get; set; }

        public Todo()
        {
            this.Created = DateTime.Now;
        }

    }
}

todotest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace todotest.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

todotest/Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using todotest.DAL;
using todotest.Models;

namespace todotest.Controllers
{
    public class TodosController : Controller
    {
        private TodoContext db = new TodoContext();
        // GET: Todos 
        public ActionResult Index(bool? done)
        {
            ViewBag.Current = null;
            List<Todo> todos = db.Todos.ToList();
            if(done != null)
            {
               ViewBag.Current = done;
               todos = todos.Where(i => i.Done == done).ToList();
            }
            return View(todos);
        }

        public ActionResult Details(int id)
        {
            Todo todo = db.Todos.Find(id); 
            return View(todo);
        }

        public ActionResult Create()
        {
            ViewBag.Create = true;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Todo todo)
        {
            if(ModelState.IsValid)
            {
                this.db.Todos.Add(todo);
                this.db.SaveChanges();
                return RedirectToAction("index");
            }
            return View();
        }

        public ActionResult Done(int id)
        {
            Todo todo = db.Todos.Find(id);
            todo.Done = !todo.Done;
            if(todo.Done)
            {
                todo.Completed = DateTime.Now;
            }
            else
            {
                todo.Completed = null;
            }
            db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

todotest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>This is a great todo app</h2>

todotest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get It Done</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color : #2C3E50">
        <div class="container" style="text-align:center">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GET IT DONE", "Create", "Todos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@(ViewBag.Create == true ? "active" : "") ">@Html.ActionLink("NEW", "Create", "Todos")</li>
                    <li class="@(ViewBag.Current == null && ViewBag.Create == null ? "active" : "") ">@Html.ActionLink("ALL", "Index", "Todos")</li>
                    <li class="@(ViewBag.Current == false ? "active" : "") ">@Html.ActionLink("ACTIVE", "Index", "Todos", new { done = false }, null)</li>
                    <li class="@(ViewBag.Current == true ? "active" : "") ">@Html.ActionLink("COMPLETED", "Index", "Todos", new { done = true }, null)</li>
                   
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        
        
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

todotest/Views/Todos/Create.cshtml
@model todotest.Models.Todo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Todo</h4>
        <hr />
     
     

        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

todotest/Views/Todos/Details.cshtml
@model todotest.Models.Todo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

todotest/Views/Todos/Index.cshtml
@model IEnumerable<todotest.Models.Todo>
@{
    ViewBag.Title = "Index";
}
<div style="text-align: center;">
    @if (ViewBag.Current == null)
    {
        <h2>Everything</h2>
    }
    @if (ViewBag.Current == false)
    {
        <h2>Things to do</h2>
    }
    @if (ViewBag.Current == true)
    {
        <h2>Things that are done</h2>
    }
    <div class="list-group">
       
        @foreach (var item in Model)
        {



            <div style="font-size:150%;">
                @if (item.Done == false)
                {
                @Html.ActionLink(item.Description, "details", new { id = item.TodoId })
                }
                @if (item.Done == true)
                {
                <s>@Html.ActionLink(item.Description, "details", new { id = item.TodoId })</s>
                } 
                |
                @Html.ActionLink("done?", "done", new { id = item.TodoId })


            </div>
            <hr />



        }


    </div>
</div>